# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Forcas' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Forcas

  target 'ForcasTests' do
    inherit! :search_paths
    pod 'Nimble'
    pod 'Quick'
  end

  target 'ForcasUITests' do
    # Pods for testing
  end

end
